const activities = [
  { id: 1, title: "Board Game Night", location: "indoor", cost: "free", description: "A classic gathering where friends compete in various tabletop games at home." },
  { id: 2, title: "Hiking Local Trails", location: "outdoor", cost: "free", description: "Explore nature and get some exercise by traversing nearby scenic paths." },
  { id: 3, title: "Fine Dining Tasting Menu", location: "indoor", cost: "$$$", description: "Experience a curated multi-course meal at a high-end restaurant." },
  { id: 4, title: "Public Park Picnic", location: "outdoor", cost: "$", description: "Pack a basket of snacks and enjoy a relaxing meal on the grass." },
  { id: 5, title: "Escape Room Challenge", location: "indoor", cost: "$$", description: "Work together to solve puzzles and find a way out of a themed locked room." },
  { id: 6, title: "Beach Volleyball", location: "outdoor", cost: "free", description: "A high-energy team sport played on the sand under the sun." },
  { id: 7, title: "Museum Gallery Tour", location: "indoor", cost: "$", description: "Walk through curated exhibits to appreciate art, history, or science." },
  { id: 8, title: "Skiing or Snowboarding", location: "outdoor", cost: "$$$", description: "Hit the slopes for an exhilarating day of winter sports." },
  { id: 9, title: "Bowling Alley", location: "indoor", cost: "$$", description: "Compete for strikes and spares in a casual, neon-lit environment." },
  { id: 10, title: "Stargazing", location: "outdoor", cost: "free", description: "Lay out a blanket and observe the constellations on a clear night." },
  { id: 11, title: "Potluck Dinner", location: "indoor", cost: "$", description: "Everyone brings a homemade dish to share for a diverse feast." },
  { id: 12, title: "Kayaking", location: "outdoor", cost: "$$", description: "Navigate local waterways using a small, narrow boat powered by a double-bladed paddle." },
  { id: 13, title: "Broadway Show", location: "indoor", cost: "$$$", description: "Watch a world-class professional theatrical performance on a grand stage." },
  { id: 14, title: "Community Garden Volunteering", location: "outdoor", cost: "free", description: "Spend time outdoors helping to plant and maintain local greenery." },
  { id: 15, title: "Laser Tag", location: "indoor", cost: "$$", description: "Engage in a futuristic battle using infrared beams in a dark arena." },
  { id: 16, title: "Outdoor Movie in the Park", location: "outdoor", cost: "$", description: "Watch a film projected onto a large screen under the open sky." },
  { id: 17, title: "Cooking Class", location: "indoor", cost: "$$$", description: "Learn professional culinary techniques and recipes from an expert chef." },
  { id: 18, title: "Rock Climbing (Bouldering)", location: "indoor", cost: "$$", description: "Scale short walls without ropes in a specialized indoor climbing gym." },
  { id: 19, title: "Backyard BBQ", location: "outdoor", cost: "$$", description: "Grill meats and vegetables while socializing in a casual outdoor setting." },
  { id: 20, title: "Movie Marathon", location: "indoor", cost: "free", description: "Settle in for a long session of watching a film series back-to-back." },
  { id: 21, title: "Hot Air Balloon Ride", location: "outdoor", cost: "$$$", description: "Float peacefully above the landscape in a basket lifted by a giant balloon." },
  { id: 22, title: "Art Museum Visit", location: "indoor", cost: "$", description: "Observe a collection of paintings, sculptures, and installations in a quiet space." },
  { id: 23, title: "Botanical Garden Walk", location: "outdoor", cost: "$", description: "Stroll through beautifully landscaped gardens featuring diverse plant species." },
  { id: 24, title: "Video Game Tournament", location: "indoor", cost: "free", description: "Compete against friends in a series of digital matches for bragging rights." },
  { id: 25, title: "Professional Sports Game", location: "outdoor", cost: "$$$", description: "Cheer for your favorite team at a major outdoor stadium event." },
  { id: 26, title: "Baking Together", location: "indoor", cost: "$", description: "Spend an afternoon in the kitchen making cookies, cakes, or pastries." },
  { id: 27, title: "Frisbee Golf", location: "outdoor", cost: "free", description: "Navigate a course by throwing discs into metal baskets." },
  { id: 28, title: "Wine Tasting", location: "indoor", cost: "$$$", description: "Sample a variety of wines while learning about their origins and flavor profiles." },
  { id: 29, title: "Camping Trip", location: "outdoor", cost: "$$", description: "Spend the night in a tent and enjoy the simplicity of the wilderness." },
  { id: 30, title: "Arcade Visit", location: "indoor", cost: "$$", description: "Play a variety of retro and modern electronic games for tickets and fun." },
  { id: 31, title: "Flea Market Browsing", location: "outdoor", cost: "$", description: "Hunt for unique treasures and vintage items at an outdoor market." },
  { id: 32, title: "Spa Day", location: "indoor", cost: "$$$", description: "Indulge in massages, facials, and relaxation treatments for total rejuvenation." },
  { id: 33, title: "Nature Photography", location: "outdoor", cost: "free", description: "Capture the beauty of local flora and fauna through a camera lens." },
  { id: 34, title: "Indoor Trampoline Park", location: "indoor", cost: "$$", description: "Jump and flip through a massive facility filled with wall-to-wall trampolines." },
  { id: 35, title: "Mini Golf", location: "outdoor", cost: "$", description: "Play through a whimsical obstacle-filled course with a putter and a colorful ball." },
  { id: 36, title: "Opera Performance", location: "indoor", cost: "$$$", description: "Attend a powerful vocal and orchestral performance in a formal setting." },
  { id: 37, title: "Bonfire on the Beach", location: "outdoor", cost: "free", description: "Gather around a fire by the ocean to roast marshmallows and chat." },
  { id: 38, title: "Book Club Meeting", location: "indoor", cost: "free", description: "Discuss a specific book over snacks and drinks with fellow readers." },
  { id: 39, title: "Horseback Riding", location: "outdoor", cost: "$$$", description: "Take a guided ride on a horse through scenic trails or fields." },
  { id: 40, title: "Trivia Night at a Pub", location: "indoor", cost: "$", description: "Test your general knowledge as a team while enjoying food and drinks." },
  { id: 41, title: "Farmers Market Visit", location: "outdoor", cost: "$", description: "Shop for fresh produce and artisanal goods from local vendors." },
  { id: 42, title: "Karaoke Bar", location: "indoor", cost: "$$", description: "Sing your favorite songs on stage or in a private room with friends." },
  { id: 43, title: "Outdoor Yoga Session", location: "outdoor", cost: "free", description: "Practice mindfulness and stretching in the fresh air of a park." },
  { id: 44, title: "Tea House Visit", location: "indoor", cost: "$$", description: "Relax with a selection of specialty teas in a cozy, quiet atmosphere." },
  { id: 45, title: "Surfing", location: "outdoor", cost: "$$", description: "Ride ocean waves on a board for a challenging and wet workout." },
  { id: 46, title: "Symphony Orchestra", location: "indoor", cost: "$$$", description: "Listen to a live classical music performance in a grand concert hall." },
  { id: 47, title: "Cycling Tour", location: "outdoor", cost: "free", description: "Ride bikes through the city or countryside to see new sights." },
  { id: 48, title: "Pottery Painting", location: "indoor", cost: "$$", description: "Choose a ceramic piece and decorate it with your own colorful designs." },
  { id: 49, title: "Theme Park Visit", location: "outdoor", cost: "$$$", description: "Spend a day riding roller coasters and enjoying various attractions." },
  { id: 50, title: "Library Study/Reading", location: "indoor", cost: "free", description: "Enjoy some quiet time reading or working together in a communal space." },
  { id: 51, title: "Dog Park Outing", location: "outdoor", cost: "free", description: "Let your pets play while you socialize with other dog owners." },
  { id: 52, title: "Jazz Club", location: "indoor", cost: "$$", description: "Enjoy live jazz music in an intimate, dimly lit venue." },
  { id: 53, title: "Street Fair", location: "outdoor", cost: "$", description: "Walk through closed-off streets filled with vendors, music, and food." },
  { id: 54, title: "Axe Throwing", location: "indoor", cost: "$$", description: "Learn to hurl axes at wooden targets in a safe, controlled environment." },
  { id: 55, title: "Canoeing", location: "outdoor", cost: "$$", description: "Paddle a light, narrow boat across a lake or down a calm river." },
  { id: 56, title: "Planetarium Show", location: "indoor", cost: "$", description: "Watch immersive projections of stars and planets on a domed ceiling." },
  { id: 57, title: "Apple Picking", location: "outdoor", cost: "$", description: "Visit an orchard to harvest fresh fruit directly from the trees." },
  { id: 58, title: "Comedy Club", location: "indoor", cost: "$$", description: "Listen to stand-up comedians perform live for an evening of laughs." },
  { id: 59, title: "Sightseeing Bus Tour", location: "outdoor", cost: "$$", description: "See city landmarks from the comfort of a large tour bus." },
  { id: 60, title: "Indoor Go-Karting", location: "indoor", cost: "$$$", description: "Race small motorized vehicles around a twisty indoor track." },
  { id: 61, title: "Bird Watching", location: "outdoor", cost: "free", description: "Use binoculars to identify and observe local bird species in the wild." },
  { id: 62, title: "Billiard/Pool Hall", location: "indoor", cost: "$", description: "Play games of pool or snooker on felt-covered tables." },
  { id: 63, title: "Geocaching", location: "outdoor", cost: "free", description: "Use GPS coordinates to hunt for hidden containers in various locations." },
  { id: 64, title: "Afternoon Tea", location: "indoor", cost: "$$$", description: "Enjoy a formal setting with tea, finger sandwiches, and scones." },
  { id: 65, title: "Tailgating", location: "outdoor", cost: "$$", description: "Host a social gathering around the open back of a vehicle before a game." },
  { id: 66, title: "Indoor Skydiving", location: "indoor", cost: "$$$", description: "Experience the sensation of freefall in a vertical wind tunnel." },
  { id: 67, title: "Fishing", location: "outdoor", cost: "$", description: "Spend a quiet day by the water trying to catch fish with a rod and reel." },
  { id: 68, title: "Dance Class", location: "indoor", cost: "$$", description: "Learn a new style of movement like salsa, ballroom, or hip-hop." },
  { id: 69, title: "Ice Skating (Outdoor Rink)", location: "outdoor", cost: "$", description: "Glide across a frozen surface in the open winter air." },
  { id: 70, title: "Aquarium Visit", location: "indoor", cost: "$$", description: "Observe thousands of sea creatures through massive glass tanks." },
  { id: 71, title: "Rowing", location: "outdoor", cost: "$$", description: "Propel a boat across the water using long wooden oars." },
  { id: 72, title: "Ping Pong Tournament", location: "indoor", cost: "free", description: "Host a competitive series of table tennis matches." },
  { id: 73, title: "Walking Architecture Tour", location: "outdoor", cost: "free", description: "Explore the city on foot to admire and learn about unique building designs." },
  { id: 74, title: "Casino Night", location: "indoor", cost: "$$$", description: "Try your luck at card games, roulette, and slot machines." },
  { id: 75, title: "Kite Flying", location: "outdoor", cost: "free", description: "Take advantage of a windy day to fly colorful kites at a park." },
  { id: 76, title: "Roller Skating", location: "indoor", cost: "$", description: "Roll around a rink to upbeat music with friends." },
  { id: 77, title: "Rock Concert (Stadium)", location: "outdoor", cost: "$$$", description: "Enjoy a large-scale musical performance with thousands of other fans." },
  { id: 78, title: "Science Center", location: "indoor", cost: "$$", description: "Interact with hands-on exhibits that explain physical and natural laws." },
  { id: 79, title: "Public Swimming Pool", location: "outdoor", cost: "$", description: "Cool off and swim laps at a community outdoor pool." },
  { id: 80, title: "Language Exchange Meetup", location: "indoor", cost: "free", description: "Practice speaking a foreign language with native speakers in a casual setting." },
  { id: 81, title: "Pickleball", location: "outdoor", cost: "free", description: "Play a fast-paced racket sport that combines elements of tennis and badminton." },
  { id: 82, title: "Poetry Slam", location: "indoor", cost: "$", description: "Listen to spoken-word artists perform their work in a competitive format." },
  { id: 83, title: "Snowshoeing", location: "outdoor", cost: "$", description: "Walk over deep snow using specialized footwear that distributes weight." },
  { id: 84, title: "VR Lounge", location: "indoor", cost: "$$", description: "Immerse yourself in virtual reality games and experiences." },
  { id: 85, title: "Drive-In Movie", location: "outdoor", cost: "$$", description: "Watch a film from the comfort of your car at a large outdoor lot." },
  { id: 86, title: "Craft Workshop", location: "indoor", cost: "$$", description: "Learn to make something specific like soap, candles, or jewelry." },
  { id: 87, title: "Outdoor Sculpture Park", location: "outdoor", cost: "free", description: "Walk through an open space dedicated to large-scale art installations." },
  { id: 88, title: "Beer Brewery Tour", location: "indoor", cost: "$", description: "See how beer is made and sample different varieties directly from the source." },
  { id: 89, title: "Paintball", location: "outdoor", cost: "$$$", description: "Compete in teams to eliminate opponents with dye-filled capsules." },
  { id: 90, title: "Indoor Swimming", location: "indoor", cost: "$", description: "Enjoy a climate-controlled environment for swimming year-round." },
  { id: 91, title: "Whitewater Rafting", location: "outdoor", cost: "$$$", description: "Navigate turbulent river rapids in an inflatable raft." },
  { id: 92, title: "Darts at a Bar", location: "indoor", cost: "$", description: "Engage in a friendly game of skill by throwing darts at a circular board." },
  { id: 93, title: "Tennis Match", location: "outdoor", cost: "free", description: "Compete in a classic racket sport on an outdoor court." },
  { id: 94, title: "Historical Mansion Tour", location: "indoor", cost: "$$", description: "Walk through a preserved historic home to see how people lived in the past." },
  { id: 95, title: "Ziplining", location: "outdoor", cost: "$$$", description: "Slide down a cable through the forest canopy for a high-speed thrill." },
  { id: 96, title: "DIY Pizza Night", location: "indoor", cost: "$", description: "Make your own pizzas from scratch with various toppings at home." },
  { id: 97, title: "Public Skating", location: "outdoor", cost: "$", description: "Enjoy a casual skate around an outdoor ice rink." },
  { id: 98, title: "Cat Cafe", location: "indoor", cost: "$", description: "Relax with a drink while interacting with resident adoptable cats." },
  { id: 100, title: "Puzzle Building", location: "indoor", cost: "free", description: "Collaboratively assemble a complex jigsaw puzzle over several hours." },
  { id: 101, title: "Charity 5K Walk", location: "outdoor", cost: "$$", description: "Walk for a cause and help raise money for local community initiatives." },
  { id: 102, title: "Jazz Brunch", location: "indoor", cost: "$$", description: "Enjoy a mid-day meal accompanied by the smooth sounds of a live jazz band." },
  { id: 103, title: "Outdoor Flea Market", location: "outdoor", cost: "free", description: "Search for vintage treasures and unique trinkets at an open-air bazaar." },
  { id: 104, title: "Bingo Night", location: "indoor", cost: "$", description: "Try your luck at winning prizes in a classic hall-style game of bingo." },
  { id: 105, title: "Snorkeling", location: "outdoor", cost: "$$", description: "Swim at the surface of the water to observe vibrant aquatic life below." },
  { id: 106, title: "Art Class (Oil Painting)", location: "indoor", cost: "$$$", description: "Learn the rich, traditional techniques of painting with oils on canvas." },
  { id: 107, title: "Fruit Picking", location: "outdoor", cost: "$", description: "Visit a local farm to harvest seasonal fruits directly from the source." },
  { id: 108, title: "Thrift Shopping", location: "indoor", cost: "$", description: "Search through second-hand stores for unique clothing and home goods." },
  { id: 109, title: "Paddleboarding", location: "outdoor", cost: "$$", description: "Balance on a large board and navigate the water with a long-handled paddle." },
  { id: 110, title: "Indoor Mini-Golf", location: "indoor", cost: "$$", description: "Navigate glow-in-the-dark obstacles in a climate-controlled putting course." },
  { id: 111, title: "Skateboarding", location: "outdoor", cost: "free", description: "Practice tricks and cruise around at a local concrete skate park." },
  { id: 112, title: "Live Podcast Recording", location: "indoor", cost: "$$", description: "Sit in the audience and watch your favorite creators record an episode live." },
  { id: 113, title: "Exploring Abandoned Places", location: "outdoor", cost: "free", description: "Safely discover the eerie beauty of forgotten structures and ruins." },
  { id: 114, title: "Sushi Making Class", location: "indoor", cost: "$$$", description: "Learn to roll your own maki and prepare nigiri with fresh ingredients." },
  { id: 115, title: "Sandcastle Building", location: "outdoor", cost: "free", description: "Use buckets and shovels to create elaborate structures on the beach." },
  { id: 116, title: "Board Game Cafe", location: "indoor", cost: "$", description: "Enjoy coffee and snacks while choosing from a massive library of tabletop games." },
  { id: 117, title: "Outdoor Basketball", location: "outdoor", cost: "free", description: "Play a high-energy pickup game at a local neighborhood court." },
  { id: 118, title: "Magic Show", location: "indoor", cost: "$$", description: "Witness mind-bending illusions and sleight of hand in an intimate theater." },
  { id: 119, title: "Corn Maze", location: "outdoor", cost: "$", description: "Work together to find your way through a giant, intricate path cut into a cornfield." },
  { id: 120, title: "Writing Circle", location: "indoor", cost: "free", description: "Share your latest creative writing pieces and give feedback to others." },
  { id: 121, title: "Whale Watching", location: "outdoor", cost: "$$$", description: "Take a boat out to sea to catch a glimpse of these massive marine mammals." },
  { id: 122, title: "Rock Climbing Gym", location: "indoor", cost: "$$", description: "Scale indoor walls using ropes and harnesses for a full-body workout." },
  { id: 123, title: "River Tubing", location: "outdoor", cost: "$", description: "Relax and float down a gentle river on a large inflatable inner tube." },
  { id: 124, title: "Antique Shopping", location: "indoor", cost: "$$", description: "Browse curated collections of historical furniture and rare collectibles." },
  { id: 125, title: "Sledding", location: "outdoor", cost: "free", description: "Race down snow-covered hills on a sled or toboggan during winter." },
  { id: 126, title: "Fondue Night", location: "indoor", cost: "$$", description: "Dip various foods into communal pots of melted cheese or chocolate." },
  { id: 127, title: "Watching the Sunset", location: "outdoor", cost: "free", description: "Find a scenic viewpoint to admire the changing colors of the evening sky." },
  { id: 128, title: "Natural History Museum", location: "indoor", cost: "$", description: "Explore exhibits featuring dinosaur skeletons, fossils, and minerals." },
  { id: 129, title: "Golfing", location: "outdoor", cost: "$$$", description: "Play a full 18-hole course at a professional-grade golf club." },
  { id: 130, title: "Acoustic Open Mic", location: "indoor", cost: "free", description: "Perform a song or listen to local musicians in a cozy, unplugged setting." },
  { id: 131, title: "Yard Sale Hopping", location: "outdoor", cost: "$", description: "Drive through neighborhoods to find cheap deals on pre-owned items." },
  { id: 132, title: "Knitting Club", location: "indoor", cost: "free", description: "Socialize while working on personal knitting or crochet projects." },
  { id: 133, title: "Disc Golf", location: "outdoor", cost: "free", description: "Navigate a park course by throwing specialized discs into metal baskets." },
  { id: 134, title: "Jewelry Making Class", location: "indoor", cost: "$$", description: "Learn to design and assemble your own necklaces, rings, or bracelets." },
  { id: 135, title: "Public Pier Fishing", location: "outdoor", cost: "$", description: "Cast a line from a wooden pier into the ocean or a large lake." },
  { id: 136, title: "Wine and Paint Night", location: "indoor", cost: "$$$", description: "Follow a step-by-step painting tutorial while sipping on glasses of wine." },
  { id: 137, title: "Exploring a Cave", location: "outdoor", cost: "$$", description: "Go underground to discover natural stalactites and rocky caverns." },
  { id: 138, title: "Indoor Soccer", location: "indoor", cost: "$", description: "Play a fast-paced game of soccer on a smaller, turf-covered indoor pitch." },
  { id: 139, title: "Outdoor Sculpture Garden", location: "outdoor", cost: "free", description: "Walk through a manicured garden filled with large-scale art installations." },
  { id: 140, title: "Home Cooking Competition", location: "indoor", cost: "$$", description: "Compete with friends to see who can make the best dish with limited ingredients." },
  { id: 141, title: "Neighborhood Walk", location: "outdoor", cost: "free", description: "Take a leisurely stroll through your local area to get some fresh air." },
  { id: 142, title: "Boutique Shopping", location: "indoor", cost: "$$$", description: "Visit small, independent shops for high-end fashion and unique items." },
  { id: 143, title: "Outdoor Photo Walk", location: "outdoor", cost: "free", description: "Walk through a scenic area and look for interesting subjects to photograph." },
  { id: 144, title: "Movie Theater", location: "indoor", cost: "$$", description: "Watch the latest blockbuster on a massive screen with surround sound." },
  { id: 145, title: "Beach Clean Up", location: "outdoor", cost: "free", description: "Volunteer your time to remove litter and keep the shoreline beautiful." },
  { id: 146, title: "Record Store Browsing", location: "indoor", cost: "$", description: "Sift through crates of vinyl records to find hidden musical gems." },
  { id: 147, title: "Garden Party", location: "outdoor", cost: "$$", description: "Host a social gathering in a backyard with drinks and light snacks." },
  { id: 148, title: "Photography Studio Session", location: "indoor", cost: "$$$", description: "Rent a professional space to take high-quality portraits or creative shots." },
  { id: 149, title: "Badminton", location: "outdoor", cost: "free", description: "Hit a shuttlecock back and forth over a net in a park setting." },
  { id: 150, title: "Yoga Studio Class", location: "indoor", cost: "$$", description: "Follow an instructor through a series of poses in a dedicated yoga space." },
  { id: 151, title: "Rooftop Drinks", location: "outdoor", cost: "$$$", description: "Enjoy cocktails and city views from a bar on top of a building." },
  { id: 152, title: "Meditation Session", location: "indoor", cost: "free", description: "Focus on mindfulness and breathing in a quiet, shared indoor space." },
  { id: 153, title: "Mushroom Foraging", location: "outdoor", cost: "free", description: "Search the forest for edible or interesting mushrooms with an expert guide." },
  { id: 154, title: "Pottery Wheel Class", location: "indoor", cost: "$$$", description: "Learn to throw clay on a spinning wheel to create bowls and vases." },
  { id: 155, title: "Scenic Train Ride", location: "outdoor", cost: "$$", description: "Sit back and relax as a train takes you through beautiful natural landscapes." },
  { id: 156, title: "Baking Bread", location: "indoor", cost: "$", description: "Spend the day kneading dough and smelling the aroma of fresh bread." },
  { id: 157, title: "Outdoor Rollerblading", location: "outdoor", cost: "free", description: "Skate along paved paths or boardwalks for a fun cardio workout." },
  { id: 158, title: "Indoor Archery", location: "indoor", cost: "$$", description: "Practice your aim with a bow and arrow at an indoor target range." },
  { id: 159, title: "Guided Canal Tour", location: "outdoor", cost: "$$", description: "Take a boat tour to learn about the history of a city's waterways." },
  { id: 160, title: "Charity Gala", location: "indoor", cost: "$$$", description: "Dress up for a formal evening of fundraising and networking." },
  { id: 161, title: "Sand Volleyball", location: "outdoor", cost: "free", description: "Dive and spike on a sandy court at the beach or a local park." },
  { id: 162, title: "Drawing at the Park", location: "outdoor", cost: "free", description: "Take a sketchbook outside and draw the landscape or people passing by." },
  { id: 163, title: "Cocktail Making Class", location: "indoor", cost: "$$$", description: "Learn the art of mixology and create your own signature drinks." },
  { id: 164, title: "Historic Site Visit", location: "outdoor", cost: "$", description: "Explore the grounds of a historical landmark or monument." },
  { id: 165, title: "Jam Session", location: "indoor", cost: "$", description: "Bring your instruments to a practice room and improvise music together." },
  { id: 166, title: "Pumpkin Patch", location: "outdoor", cost: "$", description: "Search through a field to find the perfect pumpkin for carving." },
  { id: 167, title: "Air Hockey Tournament", location: "indoor", cost: "$", description: "Compete in fast-paced games of air hockey at a local arcade." },
  { id: 168, title: "Snowball Fight", location: "outdoor", cost: "free", description: "Engage in a friendly, cold-weather battle using packed snow." },
  { id: 169, title: "Science Museum", location: "indoor", cost: "$$", description: "Interact with educational displays and scientific experiments." },
  { id: 170, title: "Local Festival", location: "outdoor", cost: "$", description: "Enjoy live music, food stalls, and community activities at a town fair." },
  { id: 171, title: "Meditation Retreat", location: "indoor", cost: "$$$", description: "Spend a weekend in silence and reflection at a dedicated center." },
  { id: 172, title: "Running Club", location: "outdoor", cost: "free", description: "Meet up with others for a group run through the city or park." },
  { id: 173, title: "Chocolate Tasting", location: "indoor", cost: "$$", description: "Sample a variety of artisanal chocolates and learn about cacao origins." },
  { id: 174, title: "Duck Feeding", location: "outdoor", cost: "free", description: "Bring healthy snacks like peas to a local pond to feed the birds." },
  { id: 175, title: "High-End Shopping", location: "indoor", cost: "$$$", description: "Visit luxury designer stores for a day of window shopping or splurging." },
  { id: 176, title: "Archery Range", location: "outdoor", cost: "$$", description: "Shoot arrows at outdoor targets to improve your precision." },
  { id: 177, title: "Foosball", location: "indoor", cost: "$", description: "Play a miniature game of soccer on a table with rotating rods." },
  { id: 178, title: "Rooftop Yoga", location: "outdoor", cost: "$$", description: "Practice your flow on a building's roof with a view of the skyline." },
  { id: 179, title: "Baking for Neighbors", location: "indoor", cost: "$", description: "Prepare sweet treats at home to distribute to people in your community." },
  { id: 180, title: "Viewing Holiday Lights", location: "outdoor", cost: "free", description: "Drive or walk through neighborhoods to see festive winter decorations." },
  { id: 181, title: "Local History Lecture", location: "indoor", cost: "free", description: "Listen to an expert talk about the past events of your specific town." },
  { id: 182, title: "Visit a Lighthouse", location: "outdoor", cost: "$", description: "Climb to the top of a coastal lighthouse for a great ocean view." },
  { id: 183, title: "Indoor Water Park", location: "indoor", cost: "$$$", description: "Enjoy slides and wave pools in a massive indoor heated facility." },
  { id: 184, title: "Street Art Walking Tour", location: "outdoor", cost: "free", description: "Search for murals and graffiti in the city's artistic districts." },
  { id: 185, title: "Candle Making", location: "indoor", cost: "$$", description: "Melt wax and add scents to create your own custom-poured candles." },
  { id: 186, title: "Birding in the Wetlands", location: "outdoor", cost: "free", description: "Use binoculars to spot rare water birds in a protected marshland." },
  { id: 187, title: "Indoor Batting Cages", location: "indoor", cost: "$", description: "Practice your baseball or softball swing against a pitching machine." },
  { id: 188, title: "Horse Racing Track", location: "outdoor", cost: "$$", description: "Watch powerful horses compete in races and enjoy the track atmosphere." },
  { id: 189, title: "Perfume Workshop", location: "indoor", cost: "$$$", description: "Mix different essential oils to create your own signature fragrance." },
  { id: 190, title: "Visit a Waterfall", location: "outdoor", cost: "free", description: "Take a hike to see water cascading over a natural cliff or rock face." },
  { id: 191, title: "Virtual Concert", location: "indoor", cost: "$", description: "Stream a high-quality live musical performance from the comfort of home." },
  { id: 192, title: "Exploring a Pier", location: "outdoor", cost: "free", description: "Walk along a wooden pier to enjoy the breeze and the view of the water." },
  { id: 193, title: "Flower Arranging", location: "indoor", cost: "$$", description: "Learn to select and group blooms to create a professional bouquet." },
  { id: 194, title: "Local Park Cleanup", location: "outdoor", cost: "free", description: "Gather with others to pick up trash and maintain your local park." },
  { id: 195, title: "Staycation", location: "indoor", cost: "$$$", description: "Book a room at a luxury local hotel to enjoy the amenities and relax." },
  { id: 196, title: "Public Tennis Courts", location: "outdoor", cost: "free", description: "Play a match on a community court available on a first-come basis." },
  { id: 197, title: "Tattoo Consultation", location: "indoor", cost: "free", description: "Meet with an artist to discuss potential designs for your next tattoo." },
  { id: 198, title: "Kite Surfing", location: "outdoor", cost: "$$$", description: "Use a large kite to pull you across the water on a specialized board." },
  { id: 199, title: "Chess in the Park", location: "outdoor", cost: "free", description: "Engage in a battle of wits at a permanent outdoor chess table." },
  { id: 200, title: "Tabletop RPG Night", location: "indoor", cost: "free", description: "Embark on an epic storytelling journey using dice and imagination." }
];

export default activities;